### PR TITLE
Fail on errors

### PR DESCRIPTION
**Pull request by artoonie**
Otherwise, ffmpeg download can fail, untarring will fail, and the buildpack build will succeed.

### CODE REVIEW

**Comment by edmorley** [comment]
@jonathanong Hi! Please can this PR be merged?

Without it use of this buildpack is dangerous, since any failures during the steps of the buildpack don't cause the build to fail, and instead the build appears successful, but will actually be missing files and therefore cause failures at runtime (ie: take a production application down).

**Comment by jonathanong** [comment]
@edmorley @artoonie added both of your as collaborators

**Comment by ridem** [comment]
@artoonie What would you like to do with this PR? Happy to add a `set -e` but I'm also fine with the way things are now.

**Comment by artoonie** [comment]
I'm fine closing this - your PR covers both curl and tar failures, and I don't see anything else likely to fail.

**Pull request closed without merging**
